@baseUrl = http://localhost:3000
@id = 0df88ac5-8ccc-4178-9e2b-98ba51e1e06b

### Create Participants
POST {{baseUrl}}/participant
Content-Type: application/json

  {
    "fullName": "Marina Morena Silva Pinto",
    "age": 24,
    "firstSemesterGrade": 5.5,
    "secondSemesterGrade": 6.0
  }

### Get All Participants
GET {{baseUrl}}/participant

### Get Participants by id
GET {{baseUrl}}/participant/{{id}}

### Update Participants by id
PATCH  {{baseUrl}}/participant/{{id}}
Content-Type: application/json

{

  "secondSemesterGrade": 5
}

### Delete Participants by id
DELETE   {{baseUrl}}/participant/{{id}} 

