@baseUrl = http://localhost:3000

### Create Participants
POST {{baseUrl}}/participant
Content-Type: application/json

{
  "fullName": "Índio medeiros",
  "age": 30,
  "firstSemesterGrade": 10,
  "secondSemesterGrade": 5,
}

### Get All Participants
GET {{baseUrl}}/participant

